apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-pvc-storage-class
spec:
  storageClassName: mongodb-storage-class
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi