apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: node-app-container
        image: loveleshagrawal/k8s-node-app:latest
        ports:
        - name: http
          containerPort: 3010
          protocol: TCP