apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app-container
        image: loveleshagrawal/k8s-node-app:latest
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: mongo-root-username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: mongo-root-password
        - name: MONGO_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: mongo-config-map
              key: MONGO_HOSTNAME
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: mongo-config-map
              key: MONGO_PORT
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              name: mongo-config-map
              key: MONGO_DB
        ports:
        - name: http
          containerPort: 3010
          protocol: TCP